//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsb.Catos.Cm.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VocabularyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VocabularyResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsb.Catos.Cm.Mobile.Resources.VocabularyResource", typeof(VocabularyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All Trucks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_AllYtList {
            get {
                return ResourceManager.GetString("WRD_CTMO_AllYtList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authority Seal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_AuthoritySeal {
            get {
                return ResourceManager.GetString("WRD_CTMO_AuthoritySeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Bay {
            get {
                return ResourceManager.GetString("WRD_CTMO_Bay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Block {
            get {
                return ResourceManager.GetString("WRD_CTMO_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block / Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_BlockArea {
            get {
                return ResourceManager.GetString("WRD_CTMO_BlockArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Cancel {
            get {
                return ResourceManager.GetString("WRD_CTMO_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Carrier Seal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_CarrierSeal {
            get {
                return ResourceManager.GetString("WRD_CTMO_CarrierSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Equipment No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_ChangeEqNo {
            get {
                return ResourceManager.GetString("WRD_CTMO_ChangeEqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Operator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_ChangeOperator {
            get {
                return ResourceManager.GetString("WRD_CTMO_ChangeOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Vessel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_ChangeVessel {
            get {
                return ResourceManager.GetString("WRD_CTMO_ChangeVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Close {
            get {
                return ResourceManager.GetString("WRD_CTMO_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Container Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_ContainerInformation {
            get {
                return ResourceManager.GetString("WRD_CTMO_ContainerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Container No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_ContainerNo {
            get {
                return ResourceManager.GetString("WRD_CTMO_ContainerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create B1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_CreateB1 {
            get {
                return ResourceManager.GetString("WRD_CTMO_CreateB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customs Seal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_CustomsSeal {
            get {
                return ResourceManager.GetString("WRD_CTMO_CustomsSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deck과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Deck {
            get {
                return ResourceManager.GetString("WRD_CTMO_Deck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End of Shift과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_EndOfShift {
            get {
                return ResourceManager.GetString("WRD_CTMO_EndOfShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Equipment {
            get {
                return ResourceManager.GetString("WRD_CTMO_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_EquipmentList {
            get {
                return ResourceManager.GetString("WRD_CTMO_EquipmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Handler과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_ErrorHandler {
            get {
                return ResourceManager.GetString("WRD_CTMO_ErrorHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gang Shift과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_GangShift {
            get {
                return ResourceManager.GetString("WRD_CTMO_GangShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Hold {
            get {
                return ResourceManager.GetString("WRD_CTMO_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HoldDeck Selection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_HoldDeckSelection {
            get {
                return ResourceManager.GetString("WRD_CTMO_HoldDeckSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job Bay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_JobBay {
            get {
                return ResourceManager.GetString("WRD_CTMO_JobBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_JobCode {
            get {
                return ResourceManager.GetString("WRD_CTMO_JobCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Location {
            get {
                return ResourceManager.GetString("WRD_CTMO_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_LogOut {
            get {
                return ResourceManager.GetString("WRD_CTMO_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Out Reason과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_LogOutReason {
            get {
                return ResourceManager.GetString("WRD_CTMO_LogOutReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Ok {
            get {
                return ResourceManager.GetString("WRD_CTMO_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Others과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Others {
            get {
                return ResourceManager.GetString("WRD_CTMO_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pool Trucks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_PoolYtList {
            get {
                return ResourceManager.GetString("WRD_CTMO_PoolYtList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Resume {
            get {
                return ResourceManager.GetString("WRD_CTMO_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_ResumeTime {
            get {
                return ResourceManager.GetString("WRD_CTMO_ResumeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Row {
            get {
                return ResourceManager.GetString("WRD_CTMO_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Seal {
            get {
                return ResourceManager.GetString("WRD_CTMO_Seal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seal Presence과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_SealPresence {
            get {
                return ResourceManager.GetString("WRD_CTMO_SealPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Search {
            get {
                return ResourceManager.GetString("WRD_CTMO_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show all Block / Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_ShowAllBlockArea {
            get {
                return ResourceManager.GetString("WRD_CTMO_ShowAllBlockArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stoppage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Stoppage {
            get {
                return ResourceManager.GetString("WRD_CTMO_Stoppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stoppage Reason과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Stoppage_Reason {
            get {
                return ResourceManager.GetString("WRD_CTMO_Stoppage_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Stoppage_Resume {
            get {
                return ResourceManager.GetString("WRD_CTMO_Stoppage_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Time {
            get {
                return ResourceManager.GetString("WRD_CTMO_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_Undo {
            get {
                return ResourceManager.GetString("WRD_CTMO_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Seal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_UpdateSeal {
            get {
                return ResourceManager.GetString("WRD_CTMO_UpdateSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_UserIdList {
            get {
                return ResourceManager.GetString("WRD_CTMO_UserIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vessel Schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_VesselSchedule {
            get {
                return ResourceManager.GetString("WRD_CTMO_VesselSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work Finished과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_WorkFinished {
            get {
                return ResourceManager.GetString("WRD_CTMO_WorkFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yard Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_YardPosition {
            get {
                return ResourceManager.GetString("WRD_CTMO_YardPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YT List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WRD_CTMO_YtList {
            get {
                return ResourceManager.GetString("WRD_CTMO_YtList", resourceCulture);
            }
        }
    }
}
