//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Tsb.Product.WB.Client.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsb.Product.WB.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static System.Drawing.Bitmap btn_down
        {
            get
            {
                object obj = ResourceManager.GetObject("btn_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap btn_up
        {
            get
            {
                object obj = ResourceManager.GetObject("btn_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Find
        {
            get
            {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Icon icon_TpMenuTitle
        {
            get
            {
                object obj = ResourceManager.GetObject("icon_TpMenuTitle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_About
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Cascade
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Cascade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_ColumnSetting
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_ColumnSetting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Configuration
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_ContainerDetail
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_ContainerDetail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Copy
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Delete
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Detail
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Detail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Excel
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Exit
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Filter
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Find
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Horizontal
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Inquiry
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Inquiry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Insert
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_New
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Option
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Option", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Paste
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Pdf
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Preview
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Print
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Save
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_SingleGrid
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_SingleGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Sort
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Sort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Summary
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap menu_Vertical
        {
            get
            {
                object obj = ResourceManager.GetObject("menu_Vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
