//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsb.Fontos.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VocabularyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VocabularyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsb.Fontos.Core.Resources.VocabularyResource", typeof(VocabularyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WRD_FTCO_ {
            get {
                return ResourceManager.GetString("WRD_FTCO_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string WRD_FTCO_Add {
            get {
                return ResourceManager.GetString("WRD_FTCO_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added QuickToolbars.
        /// </summary>
        public static string WRD_FTCO_AddedQuickToolbars {
            get {
                return ResourceManager.GetString("WRD_FTCO_AddedQuickToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AllColumns...].
        /// </summary>
        public static string WRD_FTCO_ALLCOLUMNS {
            get {
                return ResourceManager.GetString("WRD_FTCO_ALLCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application context file.
        /// </summary>
        public static string WRD_FTCO_Applicationcontextfile {
            get {
                return ResourceManager.GetString("WRD_FTCO_Applicationcontextfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Map.
        /// </summary>
        public static string WRD_FTCO_AutoMap {
            get {
                return ResourceManager.GetString("WRD_FTCO_AutoMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available QuickToolbars.
        /// </summary>
        public static string WRD_FTCO_AvailableQuickToolbars {
            get {
                return ResourceManager.GetString("WRD_FTCO_AvailableQuickToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string WRD_FTCO_btn_Apply {
            get {
                return ResourceManager.GetString("WRD_FTCO_btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string WRD_FTCO_btn_Export {
            get {
                return ResourceManager.GetString("WRD_FTCO_btn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find[Ctrl+F].
        /// </summary>
        public static string WRD_FTCO_btn_Find {
            get {
                return ResourceManager.GetString("WRD_FTCO_btn_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string WRD_FTCO_btn_Next {
            get {
                return ResourceManager.GetString("WRD_FTCO_btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string WRD_FTCO_btn_OK {
            get {
                return ResourceManager.GetString("WRD_FTCO_btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string WRD_FTCO_btn_Previous {
            get {
                return ResourceManager.GetString("WRD_FTCO_btn_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WRD_FTCO_btn_Save {
            get {
                return ResourceManager.GetString("WRD_FTCO_btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WRD_FTCO_Cancel {
            get {
                return ResourceManager.GetString("WRD_FTCO_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling.
        /// </summary>
        public static string WRD_FTCO_Canceling {
            get {
                return ResourceManager.GetString("WRD_FTCO_Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case-Sensitive.
        /// </summary>
        public static string WRD_FTCO_CaseSensitive {
            get {
                return ResourceManager.GetString("WRD_FTCO_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string WRD_FTCO_Cell {
            get {
                return ResourceManager.GetString("WRD_FTCO_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string WRD_FTCO_ChangePassword {
            get {
                return ResourceManager.GetString("WRD_FTCO_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string WRD_FTCO_CheckAll {
            get {
                return ResourceManager.GetString("WRD_FTCO_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string WRD_FTCO_Color {
            get {
                return ResourceManager.GetString("WRD_FTCO_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string WRD_FTCO_Column {
            get {
                return ResourceManager.GetString("WRD_FTCO_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Header Template.
        /// </summary>
        public static string WRD_FTCO_ColumnHeaderTemplate {
            get {
                return ResourceManager.GetString("WRD_FTCO_ColumnHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Key.
        /// </summary>
        public static string WRD_FTCO_ColumnKey {
            get {
                return ResourceManager.GetString("WRD_FTCO_ColumnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name.
        /// </summary>
        public static string WRD_FTCO_ColumnName {
            get {
                return ResourceManager.GetString("WRD_FTCO_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column seq.
        /// </summary>
        public static string WRD_FTCO_ColumnSeq {
            get {
                return ResourceManager.GetString("WRD_FTCO_ColumnSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Setting.
        /// </summary>
        public static string WRD_FTCO_ColumnSetting {
            get {
                return ResourceManager.GetString("WRD_FTCO_ColumnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnSetting_.
        /// </summary>
        public static string WRD_FTCO_ColumnSetting_ {
            get {
                return ResourceManager.GetString("WRD_FTCO_ColumnSetting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Setting List.
        /// </summary>
        public static string WRD_FTCO_ColumnSettingList {
            get {
                return ResourceManager.GetString("WRD_FTCO_ColumnSettingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string WRD_FTCO_Configuration {
            get {
                return ResourceManager.GetString("WRD_FTCO_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Type.
        /// </summary>
        public static string WRD_FTCO_ConfigurationType {
            get {
                return ResourceManager.GetString("WRD_FTCO_ConfigurationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New.
        /// </summary>
        public static string WRD_FTCO_ConfirmNew {
            get {
                return ResourceManager.GetString("WRD_FTCO_ConfirmNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Row.
        /// </summary>
        public static string WRD_FTCO_CopyRow {
            get {
                return ResourceManager.GetString("WRD_FTCO_CopyRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string WRD_FTCO_Count {
            get {
                return ResourceManager.GetString("WRD_FTCO_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRUD Operation Code.
        /// </summary>
        public static string WRD_FTCO_CRUDOperationCode {
            get {
                return ResourceManager.GetString("WRD_FTCO_CRUDOperationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Decimal Digits.
        /// </summary>
        public static string WRD_FTCO_CurrencyDecimalDigits {
            get {
                return ResourceManager.GetString("WRD_FTCO_CurrencyDecimalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Decimal Separator.
        /// </summary>
        public static string WRD_FTCO_CurrencyDecimalSeparator {
            get {
                return ResourceManager.GetString("WRD_FTCO_CurrencyDecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Group Separator.
        /// </summary>
        public static string WRD_FTCO_CurrencyGroupSeparator {
            get {
                return ResourceManager.GetString("WRD_FTCO_CurrencyGroupSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Group Sizes.
        /// </summary>
        public static string WRD_FTCO_CurrencyGroupSizes {
            get {
                return ResourceManager.GetString("WRD_FTCO_CurrencyGroupSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        public static string WRD_FTCO_CurrencySymbol {
            get {
                return ResourceManager.GetString("WRD_FTCO_CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the QuickToolbar.
        /// </summary>
        public static string WRD_FTCO_CustomizeQuickToolbar {
            get {
                return ResourceManager.GetString("WRD_FTCO_CustomizeQuickToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string WRD_FTCO_Delete {
            get {
                return ResourceManager.GetString("WRD_FTCO_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string WRD_FTCO_DeleteRow {
            get {
                return ResourceManager.GetString("WRD_FTCO_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Layout Designer.
        /// </summary>
        public static string WRD_FTCO_DetailLayout {
            get {
                return ResourceManager.GetString("WRD_FTCO_DetailLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string WRD_FTCO_Down {
            get {
                return ResourceManager.GetString("WRD_FTCO_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Column.
        /// </summary>
        public static string WRD_FTCO_EndColumn {
            get {
                return ResourceManager.GetString("WRD_FTCO_EndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end date.
        /// </summary>
        public static string WRD_FTCO_endDate {
            get {
                return ResourceManager.GetString("WRD_FTCO_endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of search.
        /// </summary>
        public static string WRD_FTCO_Endofsearch {
            get {
                return ResourceManager.GetString("WRD_FTCO_Endofsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Row.
        /// </summary>
        public static string WRD_FTCO_EndRow {
            get {
                return ResourceManager.GetString("WRD_FTCO_EndRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string WRD_FTCO_Error {
            get {
                return ResourceManager.GetString("WRD_FTCO_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string WRD_FTCO_Excel {
            get {
                return ResourceManager.GetString("WRD_FTCO_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Import Result.
        /// </summary>
        public static string WRD_FTCO_ExcelImportResult {
            get {
                return ResourceManager.GetString("WRD_FTCO_ExcelImportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Option.
        /// </summary>
        public static string WRD_FTCO_ExcelOption {
            get {
                return ResourceManager.GetString("WRD_FTCO_ExcelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string WRD_FTCO_Exclude {
            get {
                return ResourceManager.GetString("WRD_FTCO_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string WRD_FTCO_Exit {
            get {
                return ResourceManager.GetString("WRD_FTCO_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string WRD_FTCO_Field {
            get {
                return ResourceManager.GetString("WRD_FTCO_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Browser.
        /// </summary>
        public static string WRD_FTCO_FileBrowser {
            get {
                return ResourceManager.GetString("WRD_FTCO_FileBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string WRD_FTCO_FileName {
            get {
                return ResourceManager.GetString("WRD_FTCO_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string WRD_FTCO_Filter {
            get {
                return ResourceManager.GetString("WRD_FTCO_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter List.
        /// </summary>
        public static string WRD_FTCO_FilterList {
            get {
                return ResourceManager.GetString("WRD_FTCO_FilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterName_.
        /// </summary>
        public static string WRD_FTCO_FilterName_ {
            get {
                return ResourceManager.GetString("WRD_FTCO_FilterName_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Setting.
        /// </summary>
        public static string WRD_FTCO_FilterSetting {
            get {
                return ResourceManager.GetString("WRD_FTCO_FilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string WRD_FTCO_Find {
            get {
                return ResourceManager.GetString("WRD_FTCO_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string WRD_FTCO_FindNext {
            get {
                return ResourceManager.GetString("WRD_FTCO_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find What.
        /// </summary>
        public static string WRD_FTCO_FindWhat {
            get {
                return ResourceManager.GetString("WRD_FTCO_FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string WRD_FTCO_Font {
            get {
                return ResourceManager.GetString("WRD_FTCO_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Column.
        /// </summary>
        public static string WRD_FTCO_FreezeColumn {
            get {
                return ResourceManager.GetString("WRD_FTCO_FreezeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Panes.
        /// </summary>
        public static string WRD_FTCO_FreezePanes {
            get {
                return ResourceManager.GetString("WRD_FTCO_FreezePanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen Column.
        /// </summary>
        public static string WRD_FTCO_FrozenColumn {
            get {
                return ResourceManager.GetString("WRD_FTCO_FrozenColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Date Time Pattern.
        /// </summary>
        public static string WRD_FTCO_FullDateTimePattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_FullDateTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Filter.
        /// </summary>
        public static string WRD_FTCO_HeaderFilter {
            get {
                return ResourceManager.GetString("WRD_FTCO_HeaderFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string WRD_FTCO_Height {
            get {
                return ResourceManager.GetString("WRD_FTCO_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string WRD_FTCO_Information {
            get {
                return ResourceManager.GetString("WRD_FTCO_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string WRD_FTCO_Insert {
            get {
                return ResourceManager.GetString("WRD_FTCO_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row.
        /// </summary>
        public static string WRD_FTCO_InsertRow {
            get {
                return ResourceManager.GetString("WRD_FTCO_InsertRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string WRD_FTCO_lbl_ChangePassword {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string WRD_FTCO_lbl_Column {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Setting.
        /// </summary>
        public static string WRD_FTCO_lbl_ColumnSetting {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_ColumnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string WRD_FTCO_lbl_Menu {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string WRD_FTCO_lbl_OldPassword {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string WRD_FTCO_lbl_Row {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string WRD_FTCO_lbl_Stop {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string WRD_FTCO_lbl_UserID {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WRD_FTCO_lbl_Wrokspace_Name {
            get {
                return ResourceManager.GetString("WRD_FTCO_lbl_Wrokspace_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string WRD_FTCO_Login {
            get {
                return ResourceManager.GetString("WRD_FTCO_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Date Pattern.
        /// </summary>
        public static string WRD_FTCO_LongDatePattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_LongDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Time Pattern.
        /// </summary>
        public static string WRD_FTCO_LongTimePattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_LongTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string WRD_FTCO_MatchCase {
            get {
                return ResourceManager.GetString("WRD_FTCO_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched grid column.
        /// </summary>
        public static string WRD_FTCO_MatchedGridColumn {
            get {
                return ResourceManager.GetString("WRD_FTCO_MatchedGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Exactly.
        /// </summary>
        public static string WRD_FTCO_MatchExactly {
            get {
                return ResourceManager.GetString("WRD_FTCO_MatchExactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string WRD_FTCO_Menu {
            get {
                return ResourceManager.GetString("WRD_FTCO_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Day Pattern.
        /// </summary>
        public static string WRD_FTCO_MonthDayPattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_MonthDayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down row.
        /// </summary>
        public static string WRD_FTCO_Movedownrow {
            get {
                return ResourceManager.GetString("WRD_FTCO_Movedownrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up row.
        /// </summary>
        public static string WRD_FTCO_Moveuprow {
            get {
                return ResourceManager.GetString("WRD_FTCO_Moveuprow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string WRD_FTCO_name {
            get {
                return ResourceManager.GetString("WRD_FTCO_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string WRD_FTCO_NewPassword {
            get {
                return ResourceManager.GetString("WRD_FTCO_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string WRD_FTCO_NotFound {
            get {
                return ResourceManager.GetString("WRD_FTCO_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Decimal Digits.
        /// </summary>
        public static string WRD_FTCO_NumberDecimalDigits {
            get {
                return ResourceManager.GetString("WRD_FTCO_NumberDecimalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Decimal Separator.
        /// </summary>
        public static string WRD_FTCO_NumberDecimalSeparator {
            get {
                return ResourceManager.GetString("WRD_FTCO_NumberDecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Group Separator.
        /// </summary>
        public static string WRD_FTCO_NumberGroupSeparator {
            get {
                return ResourceManager.GetString("WRD_FTCO_NumberGroupSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Group Sizes.
        /// </summary>
        public static string WRD_FTCO_NumberGroupSizes {
            get {
                return ResourceManager.GetString("WRD_FTCO_NumberGroupSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string WRD_FTCO_Ok {
            get {
                return ResourceManager.GetString("WRD_FTCO_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string WRD_FTCO_OldPassword {
            get {
                return ResourceManager.GetString("WRD_FTCO_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string WRD_FTCO_OpCode {
            get {
                return ResourceManager.GetString("WRD_FTCO_OpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand.
        /// </summary>
        public static string WRD_FTCO_Operand {
            get {
                return ResourceManager.GetString("WRD_FTCO_Operand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string WRD_FTCO_Operator {
            get {
                return ResourceManager.GetString("WRD_FTCO_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other configuration type.
        /// </summary>
        public static string WRD_FTCO_Otherconfigurationtype {
            get {
                return ResourceManager.GetString("WRD_FTCO_Otherconfigurationtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Directory.
        /// </summary>
        public static string WRD_FTCO_ParentDirectory {
            get {
                return ResourceManager.GetString("WRD_FTCO_ParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string WRD_FTCO_Password {
            get {
                return ResourceManager.GetString("WRD_FTCO_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password change.
        /// </summary>
        public static string WRD_FTCO_passwordchange {
            get {
                return ResourceManager.GetString("WRD_FTCO_passwordchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Transform.
        /// </summary>
        public static string WRD_FTCO_PasteTransForm {
            get {
                return ResourceManager.GetString("WRD_FTCO_PasteTransForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string WRD_FTCO_PDF {
            get {
                return ResourceManager.GetString("WRD_FTCO_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Negative Pattern.
        /// </summary>
        public static string WRD_FTCO_PercentNegativePattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_PercentNegativePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Positive Pattern.
        /// </summary>
        public static string WRD_FTCO_PercentPositivePattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_PercentPositivePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string WRD_FTCO_Preview {
            get {
                return ResourceManager.GetString("WRD_FTCO_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Report.
        /// </summary>
        public static string WRD_FTCO_PreviewReport {
            get {
                return ResourceManager.GetString("WRD_FTCO_PreviewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Option.
        /// </summary>
        public static string WRD_FTCO_PrintOption {
            get {
                return ResourceManager.GetString("WRD_FTCO_PrintOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        public static string WRD_FTCO_PrintPreview {
            get {
                return ResourceManager.GetString("WRD_FTCO_PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string WRD_FTCO_Question {
            get {
                return ResourceManager.GetString("WRD_FTCO_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickToolbar Edit.
        /// </summary>
        public static string WRD_FTCO_QuickToolbarEdit {
            get {
                return ResourceManager.GetString("WRD_FTCO_QuickToolbarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Filter.
        /// </summary>
        public static string WRD_FTCO_RegisterFilter {
            get {
                return ResourceManager.GetString("WRD_FTCO_RegisterFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string WRD_FTCO_Remove {
            get {
                return ResourceManager.GetString("WRD_FTCO_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource file.
        /// </summary>
        public static string WRD_FTCO_Resourcefile {
            get {
                return ResourceManager.GetString("WRD_FTCO_Resourcefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string WRD_FTCO_Restore {
            get {
                return ResourceManager.GetString("WRD_FTCO_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string WRD_FTCO_Row {
            get {
                return ResourceManager.GetString("WRD_FTCO_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Header.
        /// </summary>
        public static string WRD_FTCO_RowHeader {
            get {
                return ResourceManager.GetString("WRD_FTCO_RowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string WRD_FTCO_SelectComboBoxLabel {
            get {
                return ResourceManager.GetString("WRD_FTCO_SelectComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Type.
        /// </summary>
        public static string WRD_FTCO_SelectionType {
            get {
                return ResourceManager.GetString("WRD_FTCO_SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Report.
        /// </summary>
        public static string WRD_FTCO_SelectReport {
            get {
                return ResourceManager.GetString("WRD_FTCO_SelectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default Setting.
        /// </summary>
        public static string WRD_FTCO_SetasDefaultSetting {
            get {
                return ResourceManager.GetString("WRD_FTCO_SetasDefaultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string WRD_FTCO_SheetName {
            get {
                return ResourceManager.GetString("WRD_FTCO_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Key Manager.
        /// </summary>
        public static string WRD_FTCO_ShortcutKeyManager {
            get {
                return ResourceManager.GetString("WRD_FTCO_ShortcutKeyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Date Pattern.
        /// </summary>
        public static string WRD_FTCO_ShortDatePattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_ShortDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Time Pattern.
        /// </summary>
        public static string WRD_FTCO_ShortTimePattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_ShortTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Parameter.
        /// </summary>
        public static string WRD_FTCO_ShowParameter {
            get {
                return ResourceManager.GetString("WRD_FTCO_ShowParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string WRD_FTCO_Size {
            get {
                return ResourceManager.GetString("WRD_FTCO_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string WRD_FTCO_Sort {
            get {
                return ResourceManager.GetString("WRD_FTCO_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Direction.
        /// </summary>
        public static string WRD_FTCO_SortDirection {
            get {
                return ResourceManager.GetString("WRD_FTCO_SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort List.
        /// </summary>
        public static string WRD_FTCO_SortList {
            get {
                return ResourceManager.GetString("WRD_FTCO_SortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortName_.
        /// </summary>
        public static string WRD_FTCO_SortName_ {
            get {
                return ResourceManager.GetString("WRD_FTCO_SortName_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Setting.
        /// </summary>
        public static string WRD_FTCO_SortSetting {
            get {
                return ResourceManager.GetString("WRD_FTCO_SortSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlMapperHandler setting.
        /// </summary>
        public static string WRD_FTCO_SqlMapperHandlersetting {
            get {
                return ResourceManager.GetString("WRD_FTCO_SqlMapperHandlersetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start date.
        /// </summary>
        public static string WRD_FTCO_startDate {
            get {
                return ResourceManager.GetString("WRD_FTCO_startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Row.
        /// </summary>
        public static string WRD_FTCO_StartRow {
            get {
                return ResourceManager.GetString("WRD_FTCO_StartRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string WRD_FTCO_Stop {
            get {
                return ResourceManager.GetString("WRD_FTCO_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        public static string WRD_FTCO_Stopping {
            get {
                return ResourceManager.GetString("WRD_FTCO_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to style.
        /// </summary>
        public static string WRD_FTCO_style {
            get {
                return ResourceManager.GetString("WRD_FTCO_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string WRD_FTCO_Sum {
            get {
                return ResourceManager.GetString("WRD_FTCO_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string WRD_FTCO_Summary {
            get {
                return ResourceManager.GetString("WRD_FTCO_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Filter.
        /// </summary>
        public static string WRD_FTCO_SummaryFilter {
            get {
                return ResourceManager.GetString("WRD_FTCO_SummaryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary List.
        /// </summary>
        public static string WRD_FTCO_SummaryList {
            get {
                return ResourceManager.GetString("WRD_FTCO_SummaryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string WRD_FTCO_Template {
            get {
                return ResourceManager.GetString("WRD_FTCO_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this file.
        /// </summary>
        public static string WRD_FTCO_thisfile {
            get {
                return ResourceManager.GetString("WRD_FTCO_thisfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Setting.
        /// </summary>
        public static string WRD_FTCO_tooltip_ColumnSetting {
            get {
                return ResourceManager.GetString("WRD_FTCO_tooltip_ColumnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string WRD_FTCO_tooltip_Filter {
            get {
                return ResourceManager.GetString("WRD_FTCO_tooltip_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string WRD_FTCO_tooltip_Find {
            get {
                return ResourceManager.GetString("WRD_FTCO_tooltip_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string WRD_FTCO_tooltip_Sort {
            get {
                return ResourceManager.GetString("WRD_FTCO_tooltip_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Filter.
        /// </summary>
        public static string WRD_FTCO_tooltip_SummaryFilter {
            get {
                return ResourceManager.GetString("WRD_FTCO_tooltip_SummaryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true or false.
        /// </summary>
        public static string WRD_FTCO_trueorfalse {
            get {
                return ResourceManager.GetString("WRD_FTCO_trueorfalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Interface Theme.
        /// </summary>
        public static string WRD_FTCO_UITheme {
            get {
                return ResourceManager.GetString("WRD_FTCO_UITheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string WRD_FTCO_UIThemeDefault {
            get {
                return ResourceManager.GetString("WRD_FTCO_UIThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 1.
        /// </summary>
        public static string WRD_FTCO_UIThemeStyle1 {
            get {
                return ResourceManager.GetString("WRD_FTCO_UIThemeStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 2.
        /// </summary>
        public static string WRD_FTCO_UIThemeStyle2 {
            get {
                return ResourceManager.GetString("WRD_FTCO_UIThemeStyle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 3.
        /// </summary>
        public static string WRD_FTCO_UIThemeStyle3 {
            get {
                return ResourceManager.GetString("WRD_FTCO_UIThemeStyle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 4.
        /// </summary>
        public static string WRD_FTCO_UIThemeStyle4 {
            get {
                return ResourceManager.GetString("WRD_FTCO_UIThemeStyle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 5.
        /// </summary>
        public static string WRD_FTCO_UIThemeStyle5 {
            get {
                return ResourceManager.GetString("WRD_FTCO_UIThemeStyle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 6.
        /// </summary>
        public static string WRD_FTCO_UIThemeStyle6 {
            get {
                return ResourceManager.GetString("WRD_FTCO_UIThemeStyle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck All.
        /// </summary>
        public static string WRD_FTCO_UncheckAll {
            get {
                return ResourceManager.GetString("WRD_FTCO_UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze Column.
        /// </summary>
        public static string WRD_FTCO_UnFreezeColumn {
            get {
                return ResourceManager.GetString("WRD_FTCO_UnFreezeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze Panes.
        /// </summary>
        public static string WRD_FTCO_UnFreezePanes {
            get {
                return ResourceManager.GetString("WRD_FTCO_UnFreezePanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset Column Setting.
        /// </summary>
        public static string WRD_FTCO_UnsetColumnSetting {
            get {
                return ResourceManager.GetString("WRD_FTCO_UnsetColumnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset Filter.
        /// </summary>
        public static string WRD_FTCO_UnsetFilter {
            get {
                return ResourceManager.GetString("WRD_FTCO_UnsetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset Sort.
        /// </summary>
        public static string WRD_FTCO_UnsetSort {
            get {
                return ResourceManager.GetString("WRD_FTCO_UnsetSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string WRD_FTCO_Up {
            get {
                return ResourceManager.GetString("WRD_FTCO_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Percentage.
        /// </summary>
        public static string WRD_FTCO_UsePercentage {
            get {
                return ResourceManager.GetString("WRD_FTCO_UsePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string WRD_FTCO_UserID {
            get {
                return ResourceManager.GetString("WRD_FTCO_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Validation.
        /// </summary>
        public static string WRD_FTCO_Validation {
            get {
                return ResourceManager.GetString("WRD_FTCO_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string WRD_FTCO_Value {
            get {
                return ResourceManager.GetString("WRD_FTCO_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WRD_FTCO_Warning {
            get {
                return ResourceManager.GetString("WRD_FTCO_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string WRD_FTCO_WebBrowser {
            get {
                return ResourceManager.GetString("WRD_FTCO_WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WRD_FTCO_Width {
            get {
                return ResourceManager.GetString("WRD_FTCO_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WRD_FTCO_Wrokspace_Name {
            get {
                return ResourceManager.GetString("WRD_FTCO_Wrokspace_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Type.
        /// </summary>
        public static string WRD_FTCO_Wrokspace_OpenType {
            get {
                return ResourceManager.GetString("WRD_FTCO_Wrokspace_OpenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string WRD_FTCO_X {
            get {
                return ResourceManager.GetString("WRD_FTCO_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string WRD_FTCO_Y {
            get {
                return ResourceManager.GetString("WRD_FTCO_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Month Pattern.
        /// </summary>
        public static string WRD_FTCO_YearMonthPattern {
            get {
                return ResourceManager.GetString("WRD_FTCO_YearMonthPattern", resourceCulture);
            }
        }
    }
}
