//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsb.Product.WB.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VocabularyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VocabularyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsb.Product.WB.Common.Resources.VocabularyResource", typeof(VocabularyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Bridge System.
        /// </summary>
        public static string WRD_PTWB_ApplicationName {
            get {
                return ResourceManager.GetString("WRD_PTWB_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL No.
        /// </summary>
        public static string WRD_PTWB_BLNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_BLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking No.
        /// </summary>
        public static string WRD_PTWB_BookingNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_BookingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string WRD_PTWB_CLASS {
            get {
                return ResourceManager.GetString("WRD_PTWB_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string WRD_PTWB_Clear {
            get {
                return ResourceManager.GetString("WRD_PTWB_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Option.
        /// </summary>
        public static string WRD_PTWB_DisplayOption {
            get {
                return ResourceManager.GetString("WRD_PTWB_DisplayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.Mode Location.
        /// </summary>
        public static string WRD_PTWB_DModeLocation {
            get {
                return ResourceManager.GetString("WRD_PTWB_DModeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ems.
        /// </summary>
        public static string WRD_PTWB_Ems {
            get {
                return ResourceManager.GetString("WRD_PTWB_Ems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Group.
        /// </summary>
        public static string WRD_PTWB_ExtendGroup {
            get {
                return ResourceManager.GetString("WRD_PTWB_ExtendGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Point.
        /// </summary>
        public static string WRD_PTWB_FlashPoint {
            get {
                return ResourceManager.GetString("WRD_PTWB_FlashPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR No.
        /// </summary>
        public static string WRD_PTWB_GRNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_GRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr or SDO.
        /// </summary>
        public static string WRD_PTWB_GrORSdo {
            get {
                return ResourceManager.GetString("WRD_PTWB_GrORSdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDG Class.
        /// </summary>
        public static string WRD_PTWB_IMDGClass {
            get {
                return ResourceManager.GetString("WRD_PTWB_IMDGClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimitedQuantity.
        /// </summary>
        public static string WRD_PTWB_LimitedQuantity {
            get {
                return ResourceManager.GetString("WRD_PTWB_LimitedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry No.
        /// </summary>
        public static string WRD_PTWB_LorryNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_LorryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle Job.
        /// </summary>
        public static string WRD_PTWB_Main_Button_CancleJob {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Button_CancleJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string WRD_PTWB_Main_Button_Clear {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string WRD_PTWB_Main_Button_Confirm {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print CIR.
        /// </summary>
        public static string WRD_PTWB_Main_Button_PrintCIR {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Button_PrintCIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Weight.
        /// </summary>
        public static string WRD_PTWB_Main_Button_ReadWeight {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Button_ReadWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string WRD_PTWB_Main_Button_Search {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string WRD_PTWB_Main_Button_Update {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_Category {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity Description.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_CmdtDesc {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_CmdtDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.Mode Location.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_DModeLocation {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_DModeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Weight (KG).
        /// </summary>
        public static string WRD_PTWB_Main_Grid_FirstWeight {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_FirstWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR or SDO.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_GrORSdo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_GrORSdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry No.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_LorryNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_LorryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Cargo Weight.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_NetCargoWeight {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_NetCargoWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print CIR.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_PrintCIR {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_PrintCIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Weight (KG).
        /// </summary>
        public static string WRD_PTWB_Main_Grid_SecondWeight {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_SecondWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper/Consignee.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_ShprCnsnNm {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_ShprCnsnNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN No or BL No.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_SnOrBl {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_SnOrBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Transaction No.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_TruckTransactionNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_TruckTransactionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Date.
        /// </summary>
        public static string WRD_PTWB_Main_Grid_WeightDate {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Grid_WeightDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo Infomation.
        /// </summary>
        public static string WRD_PTWB_Main_GroupBox_CargoInfomation {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_GroupBox_CargoInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string WRD_PTWB_Main_GroupBox_Monitoring {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_GroupBox_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string WRD_PTWB_Main_GroupBox_Search {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_GroupBox_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Infomation.
        /// </summary>
        public static string WRD_PTWB_Main_GroupBox_WeightInfomation {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_GroupBox_WeightInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Scale Mesurement.
        /// </summary>
        public static string WRD_PTWB_Main_GroupBox_WeightScaleMesurement {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_GroupBox_WeightScaleMesurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill of Lading No:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_BillOfLaddingNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_BillOfLaddingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo Weight:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_CargoWeight {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_CargoWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis No:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_ChassisNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_ChassisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodity Description:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_CmdtDesc {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_CmdtDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Infomation:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_FileInfomation {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_FileInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Weight Scale:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_FirstWeight {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_FirstWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate Point:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_GatePoint {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_GatePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Receipt No:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_GoodReceiptNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_GoodReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KG:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_KG {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_Lane {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry No:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_LorryNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_LorryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_Remark {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Here:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_ScanHere {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_ScanHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Weight Scale:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_SecondWeight {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_SecondWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Note No:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_ShippingNoteNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_ShippingNoteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper/Consignee Name:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_ShprOrCnsnNm {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_ShprOrCnsnNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Delivery Order No:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_SubDeliveryOrderNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_SubDeliveryOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter Name:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_TransporterNm {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_TransporterNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Call Id:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_VesselCallId {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_VesselCallId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Date From:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_WeightDateFrom {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_WeightDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Date To:.
        /// </summary>
        public static string WRD_PTWB_Main_Label_WeightDateTo {
            get {
                return ResourceManager.GetString("WRD_PTWB_Main_Label_WeightDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Pollutant.
        /// </summary>
        public static string WRD_PTWB_MarinePollutant {
            get {
                return ResourceManager.GetString("WRD_PTWB_MarinePollutant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleGrid Sample.
        /// </summary>
        public static string WRD_PTWB_Menu_SingleGrid {
            get {
                return ResourceManager.GetString("WRD_PTWB_Menu_SingleGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleGridDetial Sample.
        /// </summary>
        public static string WRD_PTWB_Menu_SingleGridDetail {
            get {
                return ResourceManager.GetString("WRD_PTWB_Menu_SingleGridDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck List.
        /// </summary>
        public static string WRD_PTWB_Menu_TruckList {
            get {
                return ResourceManager.GetString("WRD_PTWB_Menu_TruckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master BL No.
        /// </summary>
        public static string WRD_PTWB_MstBlNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_MstBlNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Cargo Weight (KG).
        /// </summary>
        public static string WRD_PTWB_NetCargoWeight {
            get {
                return ResourceManager.GetString("WRD_PTWB_NetCargoWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Group.
        /// </summary>
        public static string WRD_PTWB_PackingGrp {
            get {
                return ResourceManager.GetString("WRD_PTWB_PackingGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintCIR.
        /// </summary>
        public static string WRD_PTWB_PrintCIR {
            get {
                return ResourceManager.GetString("WRD_PTWB_PrintCIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper Shipping Name.
        /// </summary>
        public static string WRD_PTWB_ProperShippingName {
            get {
                return ResourceManager.GetString("WRD_PTWB_ProperShippingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR No.
        /// </summary>
        public static string WRD_PTWB_QRNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_QRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string WRD_PTWB_Sample {
            get {
                return ResourceManager.GetString("WRD_PTWB_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Grid.
        /// </summary>
        public static string WRD_PTWB_SampleGrid {
            get {
                return ResourceManager.GetString("WRD_PTWB_SampleGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDO No.
        /// </summary>
        public static string WRD_PTWB_SDONo {
            get {
                return ResourceManager.GetString("WRD_PTWB_SDONo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Note.
        /// </summary>
        public static string WRD_PTWB_ShippingNote {
            get {
                return ResourceManager.GetString("WRD_PTWB_ShippingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN No or BL No.
        /// </summary>
        public static string WRD_PTWB_SnNoOrBLNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_SnNoOrBLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidiary Risk.
        /// </summary>
        public static string WRD_PTWB_SubsidiaryRisk {
            get {
                return ResourceManager.GetString("WRD_PTWB_SubsidiaryRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fontos Template.
        /// </summary>
        public static string WRD_PTWB_Template {
            get {
                return ResourceManager.GetString("WRD_PTWB_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck No.
        /// </summary>
        public static string WRD_PTWB_TruckNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_TruckNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNID.
        /// </summary>
        public static string WRD_PTWB_UNID {
            get {
                return ResourceManager.GetString("WRD_PTWB_UNID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNNo.
        /// </summary>
        public static string WRD_PTWB_UNNo {
            get {
                return ResourceManager.GetString("WRD_PTWB_UNNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string WRD_PTWB_Update {
            get {
                return ResourceManager.GetString("WRD_PTWB_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Color.
        /// </summary>
        public static string WRD_PTWB_ValueColor {
            get {
                return ResourceManager.GetString("WRD_PTWB_ValueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Call ID.
        /// </summary>
        public static string WRD_PTWB_VslCallID {
            get {
                return ResourceManager.GetString("WRD_PTWB_VslCallID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Bridge.
        /// </summary>
        public static string WRD_PTWB_WB {
            get {
                return ResourceManager.GetString("WRD_PTWB_WB", resourceCulture);
            }
        }
    }
}
